---
- name: Remove Apache and Close http
  hosts: nodes
  become: yes

  tasks:
  - name: Ensure httpd not running
    service:
      name: httpd
      state: stopped

  - name: Remove httpd
    yum:
      name: httpd
      state: absent

  - name: Remove html file
    file:
      state: absent
      path: "/var/www/html/index.html"

  - name: Configure firewalld
    firewalld:
      zone: public
      port: 80/tcp
      permanent: yes
      state: disabled
    notify: Restart Firewalld

  handlers:
    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted