---
- name: Create users with folders, emails, passwords
  hosts: node1.example.com
  become: yes
  vars_files:
    - vars/users.yaml  
  tasks:
  - name: Create users from list using loop
    user:
      name: "{{ item.username }}"
      state: present
      password: "{{ item.password | password_hash('sha512') }}"
      comment: "{{ item.email }}"
      home: "{{ item.homedir }}"
      shell: "{{ item.shell }}"
    with_items: "{{ users }}"        
